version: '3'

services:

  mysql-bitcoin: 
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - QUARKUS_DATASOURCE_URL=jdbc:mysql://mysql-bitcoin:3306/place?autoReconnect=true

    volumes:
      - mysql.bitcoin:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - mysql-db

networks:
 mysql-db:
  driver: bridge

volumes:
  mysql.bitcoin: